name: Linux build with upstream zlib

on: [ workflow_dispatch,push, pull_request]

jobs:
  build:

# #     runs-on: [ ubuntu-latest, macos-latest, windows-latest]
#     runs-on: ubuntu-latest         
      
#     name: Perl1 
#     steps:
#     - name: gunzip
#       run: gunzip -h   
#     - name: bunzip2
#       run: bunzip2 -h   
#     - name: bzip2
#       run: bzip2 -h   
#     - name: zstd
#       run: zstd -h       
#     - name: diff
#       run: diff --help          
      
#   mac:

    # runs-on: macos-latest         
      
    # name: Perl2
    # steps:
    # - name: gunzip
    #   run: gunzip -h   
    # - name: bunzip2
    #   run: bunzip2 -h  
    # - name: bzip2
    #   run: bzip2 -h          
    # - name: zstd
    #   run: zstd -h    
    # - name: diff
    #   run: diff --help
    # - name: ditto
    #   run: ditto -h
      
#  windows:

# #     runs-on: [ ubuntu-latest, macos-latest, windows-latest]
#     runs-on: windows-latest     

    runs-on: [  ubuntu-latest]
      
    name: Perl3 
    steps:
    
    - name: cancel
      run: |
        gh run cancel ${{ github.run_id }}
        gh run watch ${{ github.run_id }}    

    - name: step
      run: |
        echo abc
        
        
#       run: gunzip -h   
#     - name: bunzip2
#       run: bunzip2 -h 
#     - name: bzip2
#       run: bzip2 -h          
#     - name: zstd
#       run: zstd -h     
#     - name: diff
#       run: diff --help    

    # runs-on: [ ubuntu-latest, macos-latest, windows-latest]


    
    name: 2
    steps:
    - name: home
      run: |
        perl -e '
          $a = shift;
          print "a is [$a]\n";
          $a =~ s#^(.)# "/" . lc($1) #e;
          print "a is [$a]\n";
          $a =~ s#\\#/#g;
          print "a is [$a]\n";          
          ' 'D:\abcd\efg'
      shell: bash
    
