name: Linux build with upstream zlib

on: [push, pull_request]

# upstream build derivbed from https://github.com/madler/zlib/pull/506
 

  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl:
          - '5.36'
        zlib-version:
          - 1.2.12
          
        include:
           - E1: $HOME
        #  - zlib-source: ${HOME}/upstream-zlib-source
        #    zlib-install: ${HOME}/upstream-zlib-install

    env:
      #zlib-source: ${HOME}/upstream-zlib-source
      #zlib-install: ${HOME}/upstream-zlib-install
      #ZLIB_LIB: ${HOME}/upstream-zlib-install/lib
      #ZLIB_INCLUDE: ${HOME}/upstream-zlib-install/include     
      h1: "$HOME"
      h2: "${HOME}"
      h3: $HOME
      h4: ${HOME}
     

      
    name: Perl ${{ matrix.perl }} with zlib ${{matrix.zlib-version}}
    steps:
    - uses: actions/checkout@v1

    - name: env
      run: env
      
    - name: Set Env
      run: | 
        echo "zlib-source: ${HOME}/upstream-zlib-source" >> $GITHUB_ENV
        echo "zlib-install: ${HOME}/upstream-zlib-install" >> $GITHUB_ENV
        echo "ZLIB_LIB: ${HOME}/upstream-zlib-install/lib" >> $GITHUB_ENV
        echo "ZLIB_INCLUDE: ${HOME}/upstream-zlib-install/include" >> $GITHUB_ENV

    - name: set env
      run: |
        echo AS $action_state
        echo "{environment_variable_name}={value}" >> $GITHUB_ENV
        env

    - name: Test1
      run: |
        pwd
        env
      working-directory: $zlib-source    


    - name: Checkout upstream zlib ${{matrix.zlib-version}}
      uses: actions/checkout@v2
      with:
        repository: madler/zlib
        path: $HOME/upstream-zlib-source

    - name: Build zlib ${{matrix.zlib-version}}
      run: |
        pwd
        echo h1 $h1
        echo h2 $h2
        echo h3 $h3
        echo h4 $h4
        echo E1 $E1
        echi E! ${{ env.E1 }}
        echo envhome ${{ env.HOME }}
        echo 
        echo h6 $h6
        echo HOME ${HOME}
        echo ZLIB_LIB $ZLIB_LIB
        ls
        echo ZLIB_INCLUDE $ZLIB_INCLUDE
        echo ./configure --prefix ${HOME}/upstream-zlib-install
        ./configure --prefix ${HOME}/upstream-zlib-install
        make
        make test
        make install
             
      working-directory: $HOME/upstream-zlib-source     
     
    - name: POST
      run: |
        echo ${HOME}/upstream-zlib-install
        echo ZLIB_LIB $ZLIB_LIB
        echo ZLIB_INCLUDE $ZLIB_INCLUDE        
        ls ${HOME}/upstream-zlib-install
           
      env:
        BUILD_ZLIB: 0
        ZLIB_LIB: ${{ env.HOME }}/upstream-zlib-install/lib
        ZLIB_INCLUDE: $HOME/upstream-zlib-install/include
        
