name: Linux build with upstream zlib

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
      - cron: '25 09 * * *'    # Run every Saturday
      
jobs:
  build:

    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        perl:
          - '5.38'
        zlib-version:
          - 'fred'
          - 'develop'
        zlib-native:
          - 1
          - 0
  
    env:
      zlib-source:      ${{ github.workspace }}/upstream-zlib-source
      zlib-install:     ${{ github.workspace }}/upstream-zlib-install
      ZLIB_LIB:         ${{ github.workspace }}/upstream-zlib-install/lib
      ZLIB_INCLUDE:     ${{ github.workspace }}/upstream-zlib-install/include
      ZLIB_VERSION:     ${{ matrix.zlib-version }}
      BUILD_ZLIB:       0
      ZLIB_NG_PRESENT:  1
      USE_ZLIB_NG:      ${{ matrix.zlib-native }}
      TRYIT:            ${{ matrix.zlib-native == 1 && 'OFF' || 'ON' }}
      STEP_ENABLED:     ${{ ( github.event_name != 'schedule' || ( github.event_name == 'schedule' &&  matrix.zlib-version == 'develop' ) ) && true || false }}
  
    steps:
  
    - name:  date
      run: date

    - name:  STEP_ENABLED value
      run: echo ${{ env.STEP_ENABLED }}      

    - name:  gamma
      if: env.STEP_ENABLED    
      run: echo ${{ env.STEP_ENABLED }}          
    
    - name:  delta
      if: env.STEP_ENABLED == 'true'    
      run: echo ${{ env.STEP_ENABLED }}  

    - name:  bravo
      if: env.STEP_ENABLED == true
      run: echo ${{ env.STEP_ENABLED }} 
    

    
