name: Linux build with upstream zlib

on: [push, pull_request]

# upstream build derivbed from https://github.com/madler/zlib/pull/506
 

  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl:
          - '5.36'
        zlib-version:
          - 1.2.12
          
        #include:
        #  - zlib-source: ${HOME}/upstream-zlib-source
        #    zlib-install: ${HOME}/upstream-zlib-install

    env:
      zlib-source: ${HOME}/upstream-zlib-source
      zlib-install: ${HOME}/upstream-zlib-install
      ZLIB_LIB: ${HOME}/upstream-zlib-install/lib
      ZLIB_INCLUDE: ${HOME}/upstream-zlib-install/include     
      h1: "$HOME"
      h2: "${HOME}"
      h3: $HOME
      h4: ${HOME}

      
    name: Perl ${{ matrix.perl }} with zlib :${{matrix.zlib-version}}
    steps:
    - uses: actions/checkout@v1

    - name: Checkout upstream zlib ${{matrix.zlib-version}}
      uses: actions/checkout@v2
      with:
        repository: madler/zlib
        path: ${{ env.zlib-source }}

    - name: Build zlib ${{matrix.zlib-version}}
      run: |
        pwd
        echo h1 $h1
        echo h2 $h2
        echo h3 $h3
        echo h4 $h4
        echo envhome ${{ env.HOME }}
        echo 
        echo h6 $h6
        echo HOME ${HOME}
        echo ZLIB_LIB $ZLIB_LIB
        echo ZLIB_INCLUDE $ZLIB_INCLUDE
             
      working-directory: ${{ env.zlib-source }}      
     
           
      #env:
      #  BUILD_ZLIB: 0
      #  ZLIB_LIB: ${{ matrix.zlib-install }}/lib
      #  ZLIB_INCLUDE: ${{ matrix.zlib-install }}/include
        
