name: Linux build with upstream zlib

on: [push, pull_request]

jobs:
  build:

#     runs-on: [ ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest         
      
    name: Perl 
    steps:
    - name: env
      run: gunzip -h   

  mac:

#     runs-on: [ ubuntu-latest, macos-latest, windows-latest]
    runs-on: macos-latest         
      
    name: Perl 
    steps:
    - name: env
      run: gunzip -h 
      
  windows:

#     runs-on: [ ubuntu-latest, macos-latest, windows-latest]
    runs-on: windows-latest        
      
    name: Perl 
    steps:
    - name: env
      run: gunzip -h       
