name: Linux build with upstream zlib

on: [ workflow_dispatch,push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        perl:
          - '5.38'
        zlib-version:
          - 'develop'
        zlib-native:
          - 1
          - 0
  
    env:
      zlib-source:      ${{ github.workspace }}/upstream-zlib-source
      zlib-install:     ${{ github.workspace }}/upstream-zlib-install
      ZLIB_LIB:         ${{ github.workspace }}/upstream-zlib-install/lib
      ZLIB_INCLUDE:     ${{ github.workspace }}/upstream-zlib-install/include
      ZLIB_VERSION:     ${{ matrix.zlib-version }}
      BUILD_ZLIB:       0
      ZLIB_NG_PRESENT:  1
      USE_ZLIB_NG:      ${{ matrix.zlib-native }}
      TRYIT:            ${{ matrix.zlib-native == 1 && 'OFF' || 'ON' }}
  
    steps:
  
    - name:  alpha
      run: echo ${{ env.TRYIT }}
    

    

    
