name: Linux build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release:
          - 'alpha'
  
#     env:
#       INSTALL_PATH: $HOME/${{ matrix.release }}
               
    steps:
      
    - env:
        INSTALL_PATH: $HOME/${{ matrix.release }}
    
    - uses: actions/checkout@v2
      
 

#     - name: Set
#       run: |
#         echo "::set-env name=INSTALL_PATH::$HOME/${{ matrix.release }}"
        
    - name: Show
      run: |
        echo INSTALL_PATH $INSTALL_PATH
        echo RELEASE ${{ matrix.release }}
        echo INSTALL_PATH ${{ env.INSTALL_PATH }}
        
    - name: env
      run: env
      
    - name: Check Cache
      id: my-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.INSTALL_PATH }}
        key: ${{ matrix.release }}
     
    - name: Install 
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p $INSTALL_PATH
        echo abc >$INSTALL_PATH/token
             
    - name: Work
      run: |
        cat $INSTALL_PATH/token

    
