name: Linux build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release:
          - 'alpha'
  
    env:
      INSTALL_PATH: $HOME/${{ matrix.release }}
    
    steps:
    - uses: actions/checkout@v2

    - name: env
      run: env
      
#     - name: Check Cache
#       id: my-cache
#       uses: actions/cache@v2
#       with:
#         path: ${{ env.INSTALL_PATH }}
#         key: ${{ matrix.release }}
     
    - name: Install 
#       if: steps.my-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ env.INSTALL_PATH }}
        touch ${{ env.INSTALL_PATH }}/token
             
#     - name: Work
#       run: |
#         echo INSTALL_PATH $INSTALL_PATH
#         echo RELEASE ${{ matrix.release }}
#         if [-e

    
