name: Linux build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release:
          - 'alpha'
  
    env:
      INSTALL_PATH: $HOME/raku-${{ matrix.release }}
    
    steps:
    - uses: actions/checkout@v2

    - name: env
      run: env
      
    - name: Check Cache
      id: my-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.INSTALL_PATH }}
        key: ${{ matrix.release }}
     
    - name: zip version
      run: |
        echo INSTALL_PATH $INSTALL_PATH
        echo RELEASE ${{ matrix.release }}

    
