name: Linux build with upstream zlib

on: [push, pull_request]

jobs:
  build:

# #     runs-on: [ ubuntu-latest, macos-latest, windows-latest]
#     runs-on: ubuntu-latest         
      
#     name: Perl1 
#     steps:
#     - name: gunzip
#       run: gunzip -h   
#     - name: bunzip2
#       run: bunzip2 -h   
#     - name: bzip2
#       run: bzip2 -h   
#     - name: zstd
#       run: zstd -h       
#     - name: diff
#       run: diff --help          
      
#   mac:

    runs-on: macos-latest         
      
    name: Perl2
    steps:
    - name: gunzip
      run: gunzip -h   
    - name: bunzip2
      run: bunzip2 -h  
    - name: bzip2
      run: bzip2 -h          
    - name: zstd
      run: zstd -h    
    - name: diff
      run: diff --help
    - name: ditto
      run: ditto -h
      
#  windows:

# #     runs-on: [ ubuntu-latest, macos-latest, windows-latest]
#     runs-on: windows-latest        
      
#     name: Perl3 
#     steps:
#     - name: gunzip
#       run: gunzip -h   
#     - name: bunzip2
#       run: bunzip2 -h 
#     - name: bzip2
#       run: bzip2 -h          
#     - name: zstd
#       run: zstd -h     
#     - name: diff
#       run: diff --help    
