name: Macos build

on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - 'macos-latest'
          - macos-15-intel
          - macos 26-intel
          - macos-14
          - macos-15
          - macos-26
          
          


    name: ${{ matrix.os }}
    steps:

    # - uses: actions/checkout@v3

  

    - name: iconv
      run: |
        iconv -l

    - name: clang -v
      run: clang -v


    - name: ver1
      run: clang -std=c11 -dM -E - < /dev/null | grep ISO_10646


    - name: ver2
      run: clang  -dM -E - < /dev/null | grep ISO_10646
      


    # - name: Test
    #   run: make test TEST_VERBOSE=1
