name: MacOS build 

on:
  workflow_dispatch:
  # push:
  # pull_request:
  # schedule:
  #     - cron: '25 09 * * *'    # Run every Saturday
      
jobs:
  build:

    runs-on: macos-latest
  
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    #     # perl:
    #     #   - '5.38'
    #     # zlib-version:
    #     #   - 'fred'
    #     #   - 'develop'
    #     # zlib-native:
    #     #   - 1
    #       # - 0
  
    env:
      zlib-source:      ${{ github.workspace }}/upstream-zlib-source

    steps:
    - name: install unzip
      run: |
        brew install unzip
        echo 'export PATH="/usr/local/opt/unzip/bin:$PATH"' >> /Users/runner/.bash_profile
      
    - name:  7z
      run: 7z
      
    - name:  zip -v
      run: zip -v

    - name:  unzip -v
      run: unzip -v
    

    
