name: MacOS build 

on:
  workflow_dispatch:
  # push:
  # pull_request:
  # schedule:
  #     - cron: '25 09 * * *'    # Run every Saturday
      
jobs:
  build:

    runs-on: macos-latest
  
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    #     # perl:
    #     #   - '5.38'
    #     # zlib-version:
    #     #   - 'fred'
    #     #   - 'develop'
    #     # zlib-native:
    #     #   - 1
    #       # - 0
  
    env:
      zlib-source:      ${{ github.workspace }}/upstream-zlib-source

    steps:
    - uses: Raku/setup-raku@v1
      with:
        raku-version: latest
        
    - name:  install File::Temp
      run: zef install File::Temp
              
    - name:  raku
      run: raku -e 'use File::Temp; my ($filename,$filehandle) = tempfile; say $filename'
      
    - name: install unzip
      run: |
        # port install unzip 
        # port contents unzip
        brew install --verbose unzip
        # echo 'export PATH="/usr/local/opt/unzip/bin:$PATH"' >> /Users/runner/.bash_profile

    - name:  find
      run: find /usr/local/Cellar/unzip
      
    - name:  7z
      run: 7z
      
    - name:  zip -v
      run: zip -v

    - name:  unzip -v
      run: unzip -v

    - name:  /usr/local/Cellar/unzip/6.0_8/bin/unzip -v
      run: /usr/local/Cellar/unzip/6.0_8/bin/unzip -v

    
