name: Linux build

on:
  workflow_dispatch:
  push:
  # pull_request:
  # schedule:
  #   - cron: '01 01 * * 6'    # Run every Saturday

jobs:



  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat      
    steps:

      - name: ${{ matrix.fruit }} ${{matrix.animal }} ${{ matrix.include }}
        run: echo x 
