name: Scratch

on:
  workflow_dispatch:
  push:
  # pull_request:
  # schedule:
  #   - cron: '01 01 * * 6'    # Run every Saturday

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cpa.sh {0}

    steps:
      - uses: actions/checkout@v6

      - name: Start VM
        uses: cross-platform-actions/action@v1.2.0
        with:
          operating_system: freebsd
          version: '15.0'

      - name: Test
        run: |
          uname -a
          echo $SHELL
          pwd
          ls -lah
          whoami
