name: Windows build 

on:
  workflow_dispatch:
  # push:
  # pull_request:
  # schedule:
  #     - cron: '25 09 * * *'    # Run every Saturday
      
jobs:
  build:

    runs-on: windows-latest
  
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    #     # perl:
    #     #   - '5.38'
    #     # zlib-version:
    #     #   - 'fred'
    #     #   - 'develop'
    #     # zlib-native:
    #     #   - 1
    #       # - 0
  
    env:
      zlib-source:      ${{ github.workspace }}/upstream-zlib-source

    steps:

    - name:  7z
      run: 7z
      shell: bash
      
    - name:  zip -v
      run: zip -v
      shell: bash

    - name:  unzip -v
      run: unzip -v
      shell: bash
    

    
